### ISSUE TITLE
Socket not connected error, then missing files

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/0-db-fs#22]
I have a zdb container and k3os vm deployed to the same 3Node, with zdbfs running on the VM. The zdb has one terabyte of hdd allocated and I've also patched zdbfs to accommodate a terabyte filesystem.

I launched a blockchain node container on k3s and began syncing the chain. Sometime later, the container began reporting I/O errors for the zdbfs mount. Within k3os, I saw `fuse: failed to access mountpoint /mnt/zdbfs: Socket not connected`.

After remounting the zdbfs, most data is now missing. This was on a fresh zdb, with nothing else writing to it. `df` reports an amount within expectation, but `du` and manual inspection show much less. Zdb `INFO` does not agree with either:

```
k3os-24223 [~]$ df -h | grep zdb
zdbfs-1000g    1000G  131G  870G  14% /mnt/zdbfs
```

```
k3os-24223 [~]$ du -hs /mnt/zdbfs/
132M	/mnt/zdbfs/
```

```
[2601:1c0:c803:360:b869:84ff:fe01:41c3]:9900> INFO
# server
server_name: 0-db (zdb)
server_revision: c81c6839
engine_revision: c81c6839
instance_id: 374325138
boot_time: 1623456006
uptime: 30331

# clients
clients_lifetime: 16

# stats
commands_executed: 280201
commands_failed: 4
commands_unauthorized: 0
index_disk_read_failed: 0
index_disk_write_failed: 0
data_disk_read_failed: 0
data_disk_write_failed: 0
index_disk_read_bytes: 9267176
index_disk_read_mb: 8.84
index_disk_write_bytes: 2394291
index_disk_write_mb: 2.28
data_disk_read_bytes: 13201060159
data_disk_read_mb: 12589.51
data_disk_write_bytes: 8479414059
data_disk_write_mb: 8086.60
network_rx_bytes: 8549284854
network_rx_mb: 8153.23
network_tx_bytes: 13205422554
network_tx_mb: 12593.67
```

**Comment by maxux** [comment]
Thanks for the report.

What did you patched ? If it's the `10G` report to `df`, it's not an issue and doesn't need to be fixed to be able to exceed 10G. It's just a value, it's not a limitation.

Usage reported by `df` is used according to `NSINFO` output and not `INFO`, please check result of `NSINFO zdbfs-meta` and `NSINFO zdbfs-data`.

More over, the `Socket not connected` error means that the fuse crashed. I'll open an issue to force emergency write on crash to try to keep consistancy. When the filesystem crashes, cache is lost which will lead to inconsistency. It would be more interesting to know why it crashed :p You don't have `zdbfs` output ?

**Comment by scottyeager** [comment]
My patch was simply to change [this line](https://github.com/threefoldtech/0-db-fs/blob/e11577047223c70a37d4515bf93d7cf2ba94e33c/src/zdbfs.c#L1042) to read `1000ull` for a full terabyte.

I will check `NSINFO` output and report back.

No, I didn't catch the `zdbfs` output in this case. I will be writing to a log file for all future experiments :)

**Comment by scottyeager** [comment]
I've returned to check on my `zdb` namespaces, and I actually don't see any of the expected `zdbfs` namespaces listed when accessing from `redis-cli`.

Will close this issue and start fresh with logging to see if I can reproduce.

Thanks.
