### ISSUE TITLE
Incorrect instructions in docs

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/0-db-fs#43]
In docs it mentioned this instruction
> Start a 0-db locally, in sequential mode:
zdb --mode seq
Then start zdbfs with autons option, to mount filesystem on /mnt/zdbfs:
./zdbfs -o autons /mnt/zdbfs
That's it.

This gives these errors:
```bash
❯ zdbfs -o autons /mnt/zdbfs
[+] initializing zdbfs v0.1.10
[+] blocks cache size: 4096 KB
[+] zdb: auto creating namespace
[-] zdb: (no namespace selected): nsset: This server instance is configured to use a single runtime mode
[-] zdb: could not auto set metadata namespace mode: zdbfs-temp
[-] zdb: (no namespace selected): nsset: This server instance is configured to use a single runtime mode
[-] zdb: could not auto set data namespace mode: zdbfs-data
[-] zdb: (no namespace selected): nsset: This server instance is configured to use a single runtime mode
[-] zdb: could not auto set temporary namespace mode: zdbfs-temp
```

Debugging this, the autons option will let 0dbfs calls `zdb_nsset` function which try to use zdb `nsset` command to set the namespace mode to seq

https://github.com/threefoldtech/0-db-fs/blob/df690b44561e8b7bc7d9ab8e78eba0ddc8ce179f/src/zdb.c#L191-L202

Which cause the error reported above, as setting namespace mode disabled from zdb side unless the zdb instance started without `--mode` option.

https://github.com/threefoldtech/0-db/blob/08cd0831889d55aa151b18343461ad10949d9128/zdbd/commands_namespace.c#L429-L436

Also I noticed that these errors are mostly harmless, setting namespaces mode failed but they are already created using the correct mode (zdb started in seq mode) so yes **still working** but the errors still confusing unless you dive into the code to understand what is wrong.

So I **suggest** instruction could instead referring to start the local zdb instance in **mixed mode** (without `--mode` option) to get rid of these errors.

As **alternative** to this suggestion, we can display (from 0dbfs side) this error as a warning and note alongside that this warning can be ignored if zdb instance started in seq mode.

**Comment by maxux** [comment]
Thanks for the report ! That's indeed a legacy part, it was a new feature to support `mixed mode` (first because it's the default mode and second because zdb on the grid are running `mixed mode`). Documentation were not updated since this get applied.

There is a way to know in which zdb mode is running and based on that, code can be adapted to apply the `NSSET` or not. I'll implement that to not discard the error but apply the correct settings :)

**Comment by maxux** [comment]
https://github.com/threefoldtech/0-db-fs/blob/master/src/zdb.c#L533-L553
Just saw that this was already commented in the code, haha
